### PR TITLE
Git Gut - v1.0.0

### PR DESCRIPTION
**Pull request by oraqlle**
## Details

- Welcome Page
- TL;DR - simple refence page
- Git Overview
- Installing Git
- Common Commands
- Creating a repository
- Changes, Staging and Commits
- Branches, Stashes and Tags
- Merging
- Rebasing
- Configuring Git
- GitHub Overview
- Setup
- Creating, Cloning and Uploading Remote Repositories
- Push, Pull, Fetch
- Forks
- Template Repositories
- Collaborating
- Issues
- Pull Requests
- Milestones
- Tags and Releases
- Discussions
- Licensing and OSS
- A Sample Workflow

### CODE REVIEW

**Review by Jeb14 — APPROVED** [review]
👍🏽

**Review by linton2000 — APPROVED** [review]
Looks good to me. Let's deploy this stuff 😊

**Comment by oraqlle** [comment]
I will once the rest of the @MonashDeepNeuron/executives have given it a review.

**Review by NyanKyaw — APPROVED** [review]
lg2m

**Review by Hersheys2604 — APPROVED** [review]
Sorry for the late reply, looks great to me!

**Review by AKoder123 — APPROVED** [review]

**Review by AKoder123 — APPROVED** [review]

**Review by Ozzywap — APPROVED** [review]
LGTM!

**Review by Joshua-Riantoputra — APPROVED** [review]
love the attention to detail! much content that is useful and highly practical which isn't covered anywhere else in Uni. Great step towards increasing the value MDN provides to its members

**Review by nick-chan11 — APPROVED** [review]
Very nice, covers a lot of areas and its extensive. LGTM

**Pull request merged**
